name: subtitle_translation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - nltk
  - ipykernel
  - pip
  - pip:
      - convokit
      - tqdm # Useful for tracking progress in translation/processing tasks
      - pysubs2 # A handy library specifically for subtitle editing/parsing
      - opustools
      - cinemagoer
      - transformers
      - torch
      - sentencepiece
      - sacremoses